#!/usr/bin/python3
"""Write vktrace's name tables, a C header, from the Vulkan registry.

For the enums the trace prints (formats, image layouts, descriptor types,
structure types, ...) a switch from value to name; the block size of every
uncompressed format; and for every feature structure (those extending
VkPhysicalDeviceFeatures2 whose members after sType and pNext are all VkBool32)
the names and offsets of its bits. Only names the installed header defines
outside VK_ENABLE_BETA_EXTENSIONS are written, and aliases are skipped, so the
compiler resolves every value. CMake runs it at build time.
"""
import argparse
import re
import xml.etree.ElementTree as ET

parser = argparse.ArgumentParser(description=__doc__, add_help=False, allow_abbrev=False,
                                 formatter_class=argparse.RawDescriptionHelpFormatter)
parser.add_argument("registry", metavar="VK_XML", help="the registry, vk.xml (required; no default)")
parser.add_argument("header", metavar="VULKAN_CORE_H", help="the header the layer compiles with (required; no default)")
parser.add_argument("output", metavar="OUTPUT", help="the header to write (required; no default)")
parser.add_argument("-h", "--help", action="help", help="show this help and exit (default: off)")
args = parser.parse_args()
root = ET.parse(args.registry).getroot()
header = open(args.header).read()
# Values only a beta build defines are compiled out here.
header = re.sub(r"#ifdef VK_ENABLE_BETA_EXTENSIONS\n.*?#endif", "", header, flags=re.S)
defined = set(re.findall(r"\b(VK_[A-Z0-9_]+)\b", header))
structs_defined = set(re.findall(r"typedef struct (Vk\w+) \{", header))

ENUMS = {
    "VkFormat": "VK_FORMAT_",
    "VkImageLayout": "VK_IMAGE_LAYOUT_",
    "VkDescriptorType": "VK_DESCRIPTOR_TYPE_",
    "VkStructureType": "VK_STRUCTURE_TYPE_",
    "VkImageViewType": "VK_IMAGE_VIEW_TYPE_",
    "VkImageType": "VK_IMAGE_TYPE_",
    "VkImageTiling": "VK_IMAGE_TILING_",
    "VkFilter": "VK_FILTER_",
    "VkSamplerAddressMode": "VK_SAMPLER_ADDRESS_MODE_",
    "VkSamplerMipmapMode": "VK_SAMPLER_MIPMAP_MODE_",
    "VkQueryType": "VK_QUERY_TYPE_",
    "VkComponentSwizzle": "VK_COMPONENT_SWIZZLE_",
    "VkPipelineBindPoint": "VK_PIPELINE_BIND_POINT_",
    "VkSharingMode": "VK_SHARING_MODE_",
    "VkBorderColor": "VK_BORDER_COLOR_",
    "VkCompareOp": "VK_COMPARE_OP_",
    "VkCommandBufferLevel": "VK_COMMAND_BUFFER_LEVEL_",
}

values = {name: [] for name in ENUMS}
for enums in root.findall("enums"):
    name = enums.get("name")
    if name in values:
        for e in enums.findall("enum"):
            if e.get("alias") is None and e.get("name") in defined:
                values[name].append(e.get("name"))
# Extension values live under <require> blocks.
for req in root.iter("require"):
    for e in req.findall("enum"):
        ext = e.get("extends")
        if ext in values and e.get("alias") is None and e.get("name") in defined and (
                e.get("offset") is not None or e.get("value") is not None or e.get("bitpos") is None):
            if e.get("name") not in values[ext]:
                values[ext].append(e.get("name"))


def snake(name):
    """VkImageLayout -> image_layout."""
    return re.sub(r"(?<=[a-z0-9])(?=[A-Z])", "_", name[2:]).lower()


names = {enum: [] for enum in ENUMS}
for enum, prefix in ENUMS.items():
    seen = set()
    for n in values[enum]:
        if n in seen or n.endswith("_MAX_ENUM"):
            continue
        seen.add(n)
        names[enum].append((n, n[len(prefix):] if n.startswith(prefix) else n))
longest = max(len(short) for pairs in names.values() for _, short in pairs)

lines = ["// Generated by gen_names.py from the Vulkan registry; do not edit.",
         "#ifndef DLSSLOP_AMD_TESTS_VKTRACE_VKT_NAMES_H_",
         "#define DLSSLOP_AMD_TESTS_VKTRACE_VKT_NAMES_H_",
         "",
         "#include <stddef.h>",
         "#include <stdint.h>",
         "",
         "#include <vulkan/vulkan.h>",
         "",
         "/** @brief The length of the longest name that a vkt_*_name() function gives. */",
         f"static constexpr size_t VKT_NAME_LENGTH = {longest};",
         ""]
for enum, prefix in ENUMS.items():
    lines.append(f"/** @brief A {enum}'s name without {prefix}, or nullptr for a value without one. */")
    lines.append("static inline char const *")
    lines.append(f"vkt_{snake(enum)}_name ({enum} v)")
    lines.append("{")
    lines.append("\tswitch (v) {")
    for n, short in names[enum]:
        lines.append(f"\tcase {n}: return \"{short}\";")
    lines.append("\tdefault: return nullptr;")
    lines.append("\t}")
    lines.append("}")
    lines.append("")

# Bytes per block of uncompressed formats (texelsPerBlock 1).
lines.append("/** @brief The bytes of a texel of an uncompressed format, or 0 for any other format. */")
lines.append("static inline uint32_t")
lines.append("vkt_format_bytes (VkFormat v)")
lines.append("{")
lines.append("\tswitch (v) {")
for f in root.iter("format"):
    n = f.get("name")
    if n in defined and f.get("texelsPerBlock") == "1" and f.get("blockExtent") is None:
        lines.append(f"\tcase {n}: return {int(f.get('blockSize'))};")
lines.append("\tdefault: return 0;")
lines.append("\t}")
lines.append("}")
lines.append("")

# Feature structures.
feature_structs = []
for t in root.iter("type"):
    if t.get("category") != "struct" or t.get("alias"):
        continue
    name = t.get("name")
    extends = (t.get("structextends") or "").split(",")
    if "VkPhysicalDeviceFeatures2" not in extends or name not in structs_defined:
        continue
    members = t.findall("member")
    if len(members) < 3:
        continue
    stype = members[0].get("values")
    bools = []
    ok = stype in defined
    for m in members[2:]:
        if m.get("api") == "vulkansc":
            continue
        mt = m.find("type").text
        mn = m.find("name").text
        if mt != "VkBool32" or "[" in "".join(m.itertext()):
            ok = False
            break
        bools.append(mn)
    if ok and bools:
        feature_structs.append((stype, name, bools))

core = [m.find("name").text for t in root.iter("type") if t.get("name") == "VkPhysicalDeviceFeatures"
        for m in t.findall("member")]
lines.append("/** @brief A feature bit: a VkBool32 member of a feature structure. */")
lines.append("struct vkt_feature_bit {")
lines.append("\tchar const *name;   //!< The member's name.")
lines.append("\tsize_t      offset; //!< Its offset in the structure.")
lines.append("};")
lines.append("")
lines.append("/** @brief A feature structure: one that extends VkPhysicalDeviceFeatures2 with VkBool32 members only. */")
lines.append("struct vkt_feature_struct {")
lines.append("\tchar const                   *name;  //!< The structure's name.")
lines.append("\tstruct vkt_feature_bit const *bits;  //!< Its members after sType and pNext.")
lines.append("\tVkStructureType               type;  //!< Its sType.")
lines.append("\tuint32_t                      count; //!< The bits.")
lines.append("};")
lines.append("")
lines.append("/** @brief VkPhysicalDeviceFeatures's bits. */")
lines.append("static struct vkt_feature_bit const VKT_CORE_FEATURE_BITS[] = {")
for m in core:
    lines.append(f"\t{{\"{m}\", offsetof(VkPhysicalDeviceFeatures, {m})}},")
lines.append("};")
lines.append("")
lines.append("/** @brief Every feature structure that the header defines. */")
lines.append("static struct vkt_feature_struct const VKT_FEATURE_STRUCTS[] = {")
for stype, name, bools in feature_structs:
    lines.append(f"\t{{\"{name}\", (struct vkt_feature_bit const[]){{")
    for b in bools:
        lines.append(f"\t\t{{\"{b}\", offsetof({name}, {b})}},")
    lines.append(f"\t}}, {stype}, {len(bools)}}},")
lines.append("};")
lines.append("")
lines.append("#endif /* DLSSLOP_AMD_TESTS_VKTRACE_VKT_NAMES_H_ */")
with open(args.output, "w") as out:
    out.write("\n".join(lines) + "\n")
