#!/usr/bin/python3
"""Write vktrace's name tables, a C++ header, from the Vulkan registry.

For the enums the trace prints (formats, image layouts, descriptor types,
structure types, ...) a switch from value to name; the block size of every
uncompressed format; and for every feature structure (those extending
VkPhysicalDeviceFeatures2 whose members after sType and pNext are all VkBool32)
the names and offsets of its bits. Only names the installed header defines
outside VK_ENABLE_BETA_EXTENSIONS are written, and aliases are skipped, so the
compiler resolves every value. CMake runs it at build time.
"""
import argparse
import re
import xml.etree.ElementTree as ET

parser = argparse.ArgumentParser(description=__doc__, add_help=False, allow_abbrev=False,
                                 formatter_class=argparse.RawDescriptionHelpFormatter)
parser.add_argument("registry", metavar="VK_XML", help="the registry, vk.xml (required; no default)")
parser.add_argument("header", metavar="VULKAN_CORE_H", help="the header the layer compiles with (required; no default)")
parser.add_argument("output", metavar="OUTPUT", help="the header to write (required; no default)")
parser.add_argument("-h", "--help", action="help", help="show this help and exit (default: off)")
args = parser.parse_args()
root = ET.parse(args.registry).getroot()
header = open(args.header).read()
# Values only a beta build defines are compiled out here.
header = re.sub(r"#ifdef VK_ENABLE_BETA_EXTENSIONS\n.*?#endif", "", header, flags=re.S)
defined = set(re.findall(r"\b(VK_[A-Z0-9_]+)\b", header))
structs_defined = set(re.findall(r"typedef struct (Vk\w+) \{", header))

ENUMS = {
    "VkFormat": "VK_FORMAT_",
    "VkImageLayout": "VK_IMAGE_LAYOUT_",
    "VkDescriptorType": "VK_DESCRIPTOR_TYPE_",
    "VkStructureType": "VK_STRUCTURE_TYPE_",
    "VkImageViewType": "VK_IMAGE_VIEW_TYPE_",
    "VkImageType": "VK_IMAGE_TYPE_",
    "VkImageTiling": "VK_IMAGE_TILING_",
    "VkFilter": "VK_FILTER_",
    "VkSamplerAddressMode": "VK_SAMPLER_ADDRESS_MODE_",
    "VkSamplerMipmapMode": "VK_SAMPLER_MIPMAP_MODE_",
    "VkQueryType": "VK_QUERY_TYPE_",
    "VkComponentSwizzle": "VK_COMPONENT_SWIZZLE_",
    "VkPipelineBindPoint": "VK_PIPELINE_BIND_POINT_",
    "VkSharingMode": "VK_SHARING_MODE_",
    "VkBorderColor": "VK_BORDER_COLOR_",
    "VkCompareOp": "VK_COMPARE_OP_",
    "VkCommandBufferLevel": "VK_COMMAND_BUFFER_LEVEL_",
}

values = {name: [] for name in ENUMS}
for enums in root.findall("enums"):
    name = enums.get("name")
    if name in values:
        for e in enums.findall("enum"):
            if e.get("alias") is None and e.get("name") in defined:
                values[name].append(e.get("name"))
# Extension values live under <require> blocks.
for req in root.iter("require"):
    for e in req.findall("enum"):
        ext = e.get("extends")
        if ext in values and e.get("alias") is None and e.get("name") in defined and (
                e.get("offset") is not None or e.get("value") is not None or e.get("bitpos") is None):
            if e.get("name") not in values[ext]:
                values[ext].append(e.get("name"))

lines = ["// Generated by gen_names.py from the Vulkan registry; do not edit.", "#pragma once", ""]
for enum, prefix in ENUMS.items():
    fn = enum[2:] + "Name"
    lines.append(f"inline const char* {fn}({enum} v)")
    lines.append("{")
    lines.append("    switch (v) {")
    seen = set()
    for n in values[enum]:
        if n in seen or n.endswith("_MAX_ENUM"):
            continue
        seen.add(n)
        short = n[len(prefix):] if n.startswith(prefix) else n
        lines.append(f"    case {n}: return \"{short}\";")
    lines.append("    default: return nullptr;")
    lines.append("    }")
    lines.append("}")
    lines.append("")

# Bytes per block of uncompressed formats (texelsPerBlock 1).
lines.append("inline unsigned FormatBytes(VkFormat v)")
lines.append("{")
lines.append("    switch (v) {")
for f in root.iter("format"):
    n = f.get("name")
    if n in defined and f.get("texelsPerBlock") == "1" and f.get("blockExtent") is None:
        lines.append(f"    case {n}: return {int(f.get('blockSize'))};")
lines.append("    default: return 0;")
lines.append("    }")
lines.append("}")
lines.append("")

# Feature structures.
feature_structs = []
for t in root.iter("type"):
    if t.get("category") != "struct" or t.get("alias"):
        continue
    name = t.get("name")
    extends = (t.get("structextends") or "").split(",")
    if "VkPhysicalDeviceFeatures2" not in extends or name not in structs_defined:
        continue
    members = t.findall("member")
    if len(members) < 3:
        continue
    stype = members[0].get("values")
    bools = []
    ok = stype in defined
    for m in members[2:]:
        if m.get("api") == "vulkansc":
            continue
        mt = m.find("type").text
        mn = m.find("name").text
        if mt != "VkBool32" or "[" in "".join(m.itertext()):
            ok = False
            break
        bools.append(mn)
    if ok and bools:
        feature_structs.append((stype, name, bools))

core = [m.find("name").text for t in root.iter("type") if t.get("name") == "VkPhysicalDeviceFeatures"
        for m in t.findall("member")]
lines.append("struct FeatureBitName { const char* name; unsigned offset; };")
lines.append("struct FeatureStruct { VkStructureType type; const char* name; const FeatureBitName* bits; unsigned count; };")
lines.append("inline constexpr FeatureBitName kCoreFeatureBits[] = {")
for m in core:
    lines.append(f"    {{\"{m}\", unsigned(offsetof(VkPhysicalDeviceFeatures, {m}))}},")
lines.append("};")
for stype, name, bools in feature_structs:
    lines.append(f"inline constexpr FeatureBitName k{name}Bits[] = {{")
    for b in bools:
        lines.append(f"    {{\"{b}\", unsigned(offsetof({name}, {b}))}},")
    lines.append("};")
lines.append("inline constexpr FeatureStruct kFeatureStructs[] = {")
for stype, name, bools in feature_structs:
    lines.append(f"    {{{stype}, \"{name}\", k{name}Bits, {len(bools)}}},")
lines.append("};")
with open(args.output, "w") as out:
    out.write("\n".join(lines) + "\n")
