#version 450
// SPDX-License-Identifier: MIT
// The frame's answer when a wait of the frame ran out: the first pass's input
// in place of the network's answer, dispatched over the grid that
// network_verdict.comp writes. The answer's format is its view's, RGBA32F or
// the frame's own: Vulkan 1.3 stores without a format into a format with
// STORAGE_WRITE_WITHOUT_FORMAT, as the post block does.
layout(local_size_x = 8, local_size_y = 8) in;
layout(set = 0, binding = 0) uniform writeonly image2D answer;
layout(set = 0, binding = 1) uniform sampler2D first;
layout(push_constant) uniform Push { uint width, height; } pc;

void main()
{
    const ivec2 xy = ivec2(gl_GlobalInvocationID.xy);
    if (xy.x >= int(pc.width) || xy.y >= int(pc.height)) return;
    imageStore(answer, xy, texelFetch(first, xy, 0));
}
