# Writes the SPIR-V module SPIRV as the array SYMBOL: SOURCE defines it, and
# HEADER declares it with its size as the array's bound, so that every object
# that uses it links the one definition. NAME, HEADER's path below the shader
# directory without the extension, names the include guard. The array holds
# bytes, the shape DXC's -Fh writes and the layer uses, or with WORDS set the
# module's 32-bit words, which vkCreateShaderModule takes as they are.
file(READ "${SPIRV}" bytes HEX)
string(LENGTH "${bytes}" digits)
if(WORDS)
    math(EXPR size "${digits} / 8")
    string(REGEX REPLACE "(..)(..)(..)(..)" "0x\\4\\3\\2\\1," values "${bytes}")
    set(include "#include <stdint.h>\n\n")
    set(type "uint32_t")
    set(what "words")
else()
    math(EXPR size "${digits} / 2")
    string(REGEX REPLACE "(..)" "0x\\1," values "${bytes}")
    set(include "")
    set(type "unsigned char")
    set(what "module")
endif()
get_filename_component(spirv_name "${SPIRV}" NAME)
get_filename_component(header_name "${HEADER}" NAME)
get_filename_component(source_name "${SOURCE}" NAME)
string(MAKE_C_IDENTIFIER "DLSSLOP_AMD_SHADERS_${NAME}_H_" guard)
string(TOUPPER "${guard}" guard)
file(WRITE "${HEADER}" "/** @file
 *
 * ${SYMBOL}: ${spirv_name}, which ${source_name} defines. Generated by cmake/spirv-array.cmake.
 */
#ifndef ${guard}
#define ${guard}

${include}/** @brief The SPIR-V ${what}. */
extern ${type} const ${SYMBOL}[${size}];

#endif /* ${guard} */
")
file(WRITE "${SOURCE}" "/* ${SYMBOL}: ${spirv_name}. Generated by cmake/spirv-array.cmake. */
#include \"${header_name}\"

${type} const ${SYMBOL}[] = {${values}};
")
