# Writes the SPIR-V module SPIRV as the array SYMBOL, the array shape DXC's -Fh
# writes and the layer uses: SOURCE defines it, and HEADER declares it with its
# size as the array's bound, so that the layer and its tests link the one
# definition. NAME, HEADER's path below the shader directory without the
# extension, names the include guard.
file(READ "${SPIRV}" bytes HEX)
string(LENGTH "${bytes}" digits)
math(EXPR size "${digits} / 2")
string(REGEX REPLACE "(..)" "0x\\1," bytes "${bytes}")
get_filename_component(spirv_name "${SPIRV}" NAME)
get_filename_component(header_name "${HEADER}" NAME)
get_filename_component(source_name "${SOURCE}" NAME)
string(MAKE_C_IDENTIFIER "DLSSLOP_AMD_SHADERS_${NAME}_H_" guard)
string(TOUPPER "${guard}" guard)
file(WRITE "${HEADER}" "/** @file
 *
 * ${SYMBOL}: ${spirv_name}, which ${source_name} defines. Generated by cmake/spirv-array.cmake.
 */
#ifndef ${guard}
#define ${guard}

/** @brief The SPIR-V module. */
extern unsigned char const ${SYMBOL}[${size}];

#endif /* ${guard} */
")
file(WRITE "${SOURCE}" "/* ${SYMBOL}: ${spirv_name}. Generated by cmake/spirv-array.cmake. */
#include \"${header_name}\"

unsigned char const ${SYMBOL}[] = {${bytes}};
")
